brew tap caskroom/cask

brew cask install google-chrome
brew cask install spectacle
brew cask install dropbox
brew cask install iterm2
brew cask install github
brew cask install heroku-toolbelt
brew cask install visual-studio-code
brew cask install atom
brew cask install sublime-text
brew cask install alfred
brew cask install caffeine
brew cask install joplin
brew cask install docker
brew cask install google-drive
brew cask install google-hangouts
brew cask install flux
brew cask install cheatsheet
brew cask install firefox
brew cask install hyper
brew cask install the-unarchiver
brew cask install vlc
brew cask install vanilla
brew cask install kap
brew cask install cakebrew
brew cask install spotify
brew cask install postman
brew cask install insomnia
brew cask install charles
brew cask install psequel
brew cask install postico
brew cask install bitbar
brew cask install mongodb
brew cask install skitch
brew cask install station
brew cask install steam
brew cask install spotmenu
brew cask install flycut
brew cask install numi
brew cask install lastpass
brew cask install rescuetime
