brew install git
brew install httpie
brew install postgresql
brew install go
brew install node
brew install htop
brew install calc
brew install tmux
brew install wget
brew install jq
brew install nvm
brew install tree
brew install hub
brew install cask
brew install python
brew install zsh
brew install zsh-completions
brew install yarn
brew install the_silver_searcher
brew install pgcli
