#!/usr/bin/env bash

code --install-extension alefragnani.Bookmarks
code --install-extension bajdzis.vscode-database
code --install-extension bierner.emojisense
code --install-extension brenosolutions.sqlformatter
code --install-extension bung87.rails
code --install-extension bung87.vscode-gemfile
code --install-extension christian-kohler.npm-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension discountry.react-redux-react-router-snippets
code --install-extension donjayamanne.githistory
code --install-extension doublefint.pgsql
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension HookyQR.beautify
code --install-extension Hridoy.rails-snippets
code --install-extension humao.rest-client
code --install-extension marcostazi.VS-code-drupal
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension misogi.ruby-rubocop
code --install-extension mohsen1.prettify-json
code --install-extension ms-python.python
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension noku.rails-run-spec-vscode
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension pkosta2005.heroku-command
code --install-extension rebornix.ruby
code --install-extension Shan.code-settings-sync
code --install-extension sporto.rails-go-to-spec
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vscodevim.vim
code --install-extension WakaTime.vscode-wakatime
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme
